server:
  port: 66
dept:
  name: xiaoqiang
  address: beijing
  dev: attr-dev
deptdev:
  name: dev-name
com:
  mrk:
    async:
      override-default-executor: true
      auto-create-default: false
      auto-create-customer: true
      config:
        myAsyncTaskPool:
          thread-group-name: my-async
          pool:
            core-size: 2
            max-size: 5
            queue-capacity: 10
            keep-alive: 60S
    thread:
      enable: true
      before-clear: true
      pools:
        myPool1:
          thread-group-name: gn1
          before-clear: false
          config:
            core-size: 2
            max-size: 5
            queue-capacity: 10
            keep-alive: 60S
        myPool2:
          config:
            core-size: 10
            max-size: 50
            queue-capacity: 100
            keep-alive: 60S


spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 200
        keep-alive: 60S
      thread-name-prefix: "custom-async-"
  jackson:
    time-zone: GMT+8
  datasource:
    name: datasource
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://123.57.250.205:6446/db1?allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#      url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B0
#      url: jdbc:mysql://127.0.0.1:8066/TESTDB?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

#      url: jdbc:mysql://127.0.0.1:3306/db1?allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#      username: root
#      password: 12345678

      url: jdbc:mysql://dev-03.cluster-c9qe4y0vrvda.rds.cn-northwest-1.amazonaws.com.cn:3306/eclinical_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&serverTimeZone=UTC
      username: root
      password: 8YTJWOuA7XRK17wRQnw4

#      url: jdbc:oracle:thin:@140.100.130.112:1521:orcl
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      username: vsta
#      password: vsta

      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  #热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources/templates
      exclude: WEB-INF/**
  #静态资源，添加templates为了访问html同目录下js
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  application:
    name: springbootDemo
  # 模板配置
  thymeleaf:
    # 是否为Web框架启用Thymeleaf视图分辨率。
    enabled: true
    # 是否启用模板缓存。
    cache: false
    # 编码格式, 默认UTF-8
    encoding: UTF-8
    # 应用于模板的模板模式。另请参阅Thymeleaf的TemplateMode枚举。
    mode: HTML
    # 后缀 默认 .html
    suffix: .html
    # 模板文件存放位置  , 默认 classpath:/templates/
    prefix: classpath:/templates/

mybatis:
  #这里是mapper的配置文件
  mapper-locations: classpath:com.example.demo.mapper/*/*.xml
  #这里是实体类的包
  type-aliases-package: com.example.demo.model
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
