server:
  port: 80
spring:
  datasource:
    name: datasource
    url: jdbc:mysql://127.0.0.1:3306/hello?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources/templates
      exclude: WEB-INF/**
  #静态资源，添加templates为了访问html同目录下js
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  application:
    name: thymeleaf
  # 模板配置
  thymeleaf:
    # 是否为Web框架启用Thymeleaf视图分辨率。
    enabled: true
    # 是否启用模板缓存。
    cache: false
    # 编码格式, 默认UTF-8
    encoding: UTF-8
    # 应用于模板的模板模式。另请参阅Thymeleaf的TemplateMode枚举。
    mode: HTML
    # 后缀 默认 .html
    suffix: .html
    # 模板文件存放位置  , 默认 classpath:/templates/
    prefix: classpath:/templates/

mybatis:
  #这里是mapper的配置文件
  mapper-locations: classpath:com.example.demo.mapper/*/*.xml
  #这里是实体类的包
  type-aliases-package: com.example.demo.model
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
dept:
  name: 11
